In [1]:
import numpy as np
import matplotlib.pyplot as plt
import csv
import pandas
# Changes imports to look one folder up.
import sys, os
sys.path.insert(0, os.path.abspath('..'))
from Sophos import SophosNet as sn

In [2]:
pandata = pandas.read_csv('example_data/UCI_Credit_Card.csv')
pandata = pandata.drop('ID', axis=1)
pandata_test_data_size = int(len(pandata) * .1)
pandata_test_data = pandata.tail(pandata_test_data_size)
pandata = pandata.head(len(pandata)-pandata_test_data_size)
pandata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27000 entries, 0 to 26999
Data columns (total 24 columns):
LIMIT_BAL                     27000 non-null float64
SEX                           27000 non-null int64
EDUCATION                     27000 non-null int64
MARRIAGE                      27000 non-null int64
AGE                           27000 non-null int64
PAY_0                         27000 non-null int64
PAY_2                         27000 non-null int64
PAY_3                         27000 non-null int64
PAY_4                         27000 non-null int64
PAY_5                         27000 non-null int64
PAY_6                         27000 non-null int64
BILL_AMT1                     27000 non-null float64
BILL_AMT2                     27000 non-null float64
BILL_AMT3                     27000 non-null float64
BILL_AMT4                     27000 non-null float64
BILL_AMT5                     27000 non-null float64
BILL_AMT6                     27000 non-null float64
PAY_AMT1  

In [27]:
#Use to normalize continuous values (X−μ)/σ
limitBalMean = np.mean(pandata['LIMIT_BAL'].tolist())
limitBalStd = np.std(pandata['LIMIT_BAL'].tolist())

ageMean = np.mean(pandata['AGE'].tolist())
ageStd = np.std(pandata['AGE'].tolist())

pay0Mean = np.mean(pandata['PAY_0'].tolist())
pay0Std = np.std(pandata['PAY_0'].tolist())

pay2Mean = np.mean(pandata['PAY_2'].tolist())
pay2Std = np.std(pandata['PAY_2'].tolist())

pay3Mean = np.mean(pandata['PAY_3'].tolist())
pay3Std = np.std(pandata['PAY_3'].tolist())

pay4Mean = np.mean(pandata['PAY_4'].tolist())
pay4Std = np.std(pandata['PAY_4'].tolist())

pay5Mean = np.mean(pandata['PAY_5'].tolist())
pay5Std = np.std(pandata['PAY_5'].tolist())

pay6Mean = np.mean(pandata['PAY_6'].tolist())
pay6Std = np.std(pandata['PAY_6'].tolist())

billAmt1Mean = np.mean(pandata['BILL_AMT1'].tolist())
billAmt1Std = np.std(pandata['BILL_AMT1'].tolist())

billAmt2Mean = np.mean(pandata['BILL_AMT2'].tolist())
billAmt2Std = np.std(pandata['BILL_AMT2'].tolist())

billAmt3Mean = np.mean(pandata['BILL_AMT3'].tolist())
billAmt3Std = np.std(pandata['BILL_AMT3'].tolist())

billAmt4Mean = np.mean(pandata['BILL_AMT4'].tolist())
billAmt4Std = np.std(pandata['BILL_AMT4'].tolist())

billAmt5Mean = np.mean(pandata['BILL_AMT5'].tolist())
billAmt5Std = np.std(pandata['BILL_AMT5'].tolist())

billAmt6Mean = np.mean(pandata['BILL_AMT6'].tolist())
billAmt6Std = np.std(pandata['BILL_AMT6'].tolist())

payAmt1Mean = np.mean(pandata['PAY_AMT1'].tolist())
payAmt1Std = np.std(pandata['PAY_AMT1'].tolist())

payAmt2Mean = np.mean(pandata['PAY_AMT2'].tolist())
payAmt2Std = np.std(pandata['PAY_AMT2'].tolist())

payAmt3Mean = np.mean(pandata['PAY_AMT3'].tolist())
payAmt3Std = np.std(pandata['PAY_AMT3'].tolist())

payAmt4Mean = np.mean(pandata['PAY_AMT4'].tolist())
payAmt4Std = np.std(pandata['PAY_AMT4'].tolist())

payAmt5Mean = np.mean(pandata['PAY_AMT5'].tolist())
payAmt5Std = np.std(pandata['PAY_AMT5'].tolist())

payAmt6Mean = np.mean(pandata['PAY_AMT6'].tolist())
payAmt6Std = np.std(pandata['PAY_AMT6'].tolist())

In [3]:
def convert_data(inputVector):
    # LIMIT_BAL                     27000 non-null float64
    # SEX                           27000 non-null int64
    # EDUCATION                     27000 non-null int64
    # MARRIAGE                      27000 non-null int64
    # AGE                           27000 non-null int64
    # PAY_0                         27000 non-null int64
    # PAY_2                         27000 non-null int64
    # PAY_3                         27000 non-null int64
    # PAY_4                         27000 non-null int64
    # PAY_5                         27000 non-null int64
    # PAY_6                         27000 non-null int64
    # BILL_AMT1                     27000 non-null float64
    # BILL_AMT2                     27000 non-null float64
    # BILL_AMT3                     27000 non-null float64
    # BILL_AMT4                     27000 non-null float64
    # BILL_AMT5                     27000 non-null float64
    # BILL_AMT6                     27000 non-null float64
    # PAY_AMT1                      27000 non-null float64
    # PAY_AMT2                      27000 non-null float64
    # PAY_AMT3                      27000 non-null float64
    # PAY_AMT4                      27000 non-null float64
    # PAY_AMT5                      27000 non-null float64
    # PAY_AMT6                      27000 non-null float64
    # Combine 'other' and 'unknown' values.
    if (inputVector[2] > 4):
        inputVector[2] = 4
    #normalize continuous values X−μ)/σ
    inputVector[0] = (inputVector[0] - limitBalMean) / limitBalStd
    inputVector[4] = (inputVector[4] - ageMean) / ageStd
    inputVector[5] = (inputVector[5] - pay0Mean) / pay0Std
    inputVector[6] = (inputVector[6] - pay2Mean) / pay2Std
    inputVector[7] = (inputVector[7] - pay3Mean) / pay3Std
    inputVector[8] = (inputVector[8] - pay4Mean) / pay4Std
    inputVector[9] = (inputVector[9] - pay5Mean) / pay5Std
    inputVector[10] = (inputVector[10] - pay6Mean) / pay6Std
    inputVector[11] = (inputVector[11] - billAmt1Mean) / billAmt1Std
    inputVector[12] = (inputVector[12] - billAmt2Mean) / billAmt2Std
    inputVector[13] = (inputVector[13] - billAmt3Mean) / billAmt3Std
    inputVector[14] = (inputVector[14] - billAmt4Mean) / billAmt4Std
    inputVector[15] = (inputVector[15] - billAmt5Mean) / billAmt5Std
    inputVector[16] = (inputVector[16] - billAmt6Mean) / billAmt6Std
    inputVector[17] = (inputVector[17] - payAmt1Mean) / payAmt1Std
    inputVector[18] = (inputVector[18] - payAmt2Mean) / payAmt2Std
    inputVector[19] = (inputVector[19] - payAmt3Mean) / payAmt3Std
    inputVector[20] = (inputVector[20] - payAmt4Mean) / payAmt4Std
    inputVector[21] = (inputVector[21] - payAmt5Mean) / payAmt5Std
    inputVector[22] = (inputVector[22] - payAmt6Mean) / payAmt6Std
    return inputVector

In [ ]:
for i, row in pandata.iterrows():
    pandata.loc[i] = convert_data(pandata.loc[i])

In [4]:
model = sn.Model()
#Layer(num_inputs, num_neurons)
l1 = sn.Layer(23, 1)
a1 = sn.Activation('sigmoid')
model.add(l1)
model.add(a1)
model.setLearningRate(0.1)

In [ ]:
model.setLearningRate(0.05)

In [ ]:
# Test data
print(np.matrix(pandata_test_data.iloc[0].values[None, :23]))
print(type(np.matrix(pandata_test_data.iloc[0].values[None, :23])))

print(np.matrix([pandata_test_data.iloc[0]]))
print(type(np.matrix([pandata_test_data.iloc[0]])))

#print(pandata_test_data.loc[j].values[None, :23][0])

In [ ]:
plotError = list()
batch = 100
#num_tests = iterations * batch
#iterations is run-through of each batch, which is part of the entire set
#epoch is one run-through of EACH sample
for i, row in pandata.iterrows():
    train_row = np.matrix(pandata.loc[i].values[None, :23])
    default_next_month = np.matrix(pandata.loc[i]['default.payment.next.month'])
    model.train(train_row, default_next_month)
    print(train_row)
    print(default_next_month)
    if i % batch == 0:
        num_correct = 0
        for j, row in pandata_test_data.iterrows():
            #print(np.matrix(pandata_test_data.loc[j].values[None, :23][0]))
            
            r = model.predictStep(np.matrix(pandata_test_data.loc[j].values[None, :23][0]))
            #print('r:' + str(r))
            #print('actually:' + str(pandata_test_data.loc[j]['default.payment.next.month']))
            if r == pandata_test_data.loc[j]['default.payment.next.month']:
                num_correct += 1
            #print(num_correct)
        accuracy = num_correct/len(pandata_test_data)
        print('# Correct:' + str(num_correct))
        print('Batch ' + str(i / batch) + ' accuracy:' + str(accuracy))
        plotError.append(accuracy)

In [ ]:
plt.plot(plotError)
plt.show()

In [26]:
print(l1.getWeights())

[[ 0.65521355]
 [ 0.47919486]
 [ 0.05436008]
 [ 0.21015581]
 [ 0.69818667]
 [ 0.78036917]
 [ 0.31449949]
 [ 0.38482461]
 [ 0.94851438]
 [ 0.52032423]
 [ 0.57930065]
 [ 0.87576045]
 [ 0.3434434 ]
 [ 0.07423028]
 [ 0.96515577]
 [ 0.85456491]
 [ 0.13848934]
 [ 0.16899082]
 [ 0.64547928]
 [ 0.64756882]
 [ 0.89171868]
 [ 0.8804276 ]
 [ 0.88842828]
 [ 0.4707546 ]]


In [6]:
model.feed(np.matrix(pandata_test_data.iloc[0].values[None, :23][0]))

matrix([[ 1.]])

In [14]:
l1out = l1.feed(np.matrix(pandata_test_data.iloc[0].values[None, :23][0]))
print(l1out)
# print(a1.feed(l1out))

[[ 243889.0236948]]


In [10]:
train_row = np.matrix(pandata_test_data.iloc[1].values[None, :23][0])
default_next_month = pandata.iloc[0]['default.payment.next.month']
y = np.matrix('0')
model.train(train_row, y)

dE/dOut:  [[ 1.]]
dOut/dNet:  [[ 0.]]
Updated Weights:  [[ 0.65521355]
 [ 0.47919486]
 [ 0.05436008]
 [ 0.21015581]
 [ 0.69818667]
 [ 0.78036917]
 [ 0.31449949]
 [ 0.38482461]
 [ 0.94851438]
 [ 0.52032423]
 [ 0.57930065]
 [ 0.87576045]
 [ 0.3434434 ]
 [ 0.07423028]
 [ 0.96515577]
 [ 0.85456491]
 [ 0.13848934]
 [ 0.16899082]
 [ 0.64547928]
 [ 0.64756882]
 [ 0.89171868]
 [ 0.8804276 ]
 [ 0.88842828]
 [ 0.4707546 ]]


matrix([[ 1.]])

In [9]:
print(np.matrix(pandata_test_data.iloc[1].values[None, :23][0]))

[[  5.00000000e+04   1.00000000e+00   2.00000000e+00   1.00000000e+00
    4.10000000e+01   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00   8.98800000e+03
    6.84900000e+03   7.47100000e+03   8.04300000e+03   1.95260000e+04
    7.56400000e+03   1.20000000e+03   2.00000000e+03   2.00000000e+03
    3.00000000e+03   1.00000000e+03   1.06400000e+04]]


In [ ]:
print(y)